cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [905.54391124, 905.54391124, 665.0164321, 368.60133365]
  resolution: [1280, 800]
  rostopic: /ovc/rgb/image_color
